Treinamento/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('simplemooc.urls' ,namespace='simplemooc')),
    url(
        r'^login/$', auth_views.login, {'template_name': 'login.html'},
        name='login'
    ),
    url(r'^logout/$', auth_views.logout, {'next_page': 'simplemooc:home'}, name='logout'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^user/add/$', views.CreateUser.as_view(), name='createUser'),
    url(r'^edit/$', views.Edit_user, name='edit_user'),
    url(r'^courses/student/$', views.CoursesStudent.as_view(), name='student_courses'),
    url(r'^subscription/(?P<slug>[\w_-]+)/$', views.subscription, name='subscription')
]

simplemooc/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from simplemooc import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^courses/$', views.CourseView.as_view(), name='courses'),
    url(r'^course/(?P<slug>[\w_-]+)/$', views.ShowCourseView.as_view(), name='detail'),
    url(r'^course/category/(?P<slug>[\w_-]+)/$', views.ShowCategoryView.as_view(), name='category'),
    url(r'^category/add/$', views.CreateCategory.as_view(), name='createCategory'),
    url(r'^module/add$', views.CreateModule.as_view(), name='createModule'),
    url(r'^teacher/add$', views.CreateTeacher.as_view(), name='createTeacher'),
    url(r'^course/add$', views.CreateCourse.as_view(), name='createCourse'),
    url(r'^course/update/(?P<slug>[\w_-]+)/$', views.UpdateCourse.as_view(), name='updateCourse'),
    url(r'^course/delete/(?P<slug>[\w_-]+)/$', views.DeleteCourse.as_view(), name='deleteCourse'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
]

simplemooc/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Category(models.Model):
    name = models.CharField(_('Name'), max_length=100)
    slug = models.SlugField(_('Identify'), max_length=100)

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def get_absolute_url(self):
        return reverse('simplemooc:courses')

    def __str__(self):
        return self.name

class Teacher(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    class Meta:
        verbose_name = 'Professor'
        verbose_name_plural = 'Professores'

    def get_absolute_url(self):
        return reverse('simplemooc:courses')

    def __str__(self):
        return self.name

class Modules(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    description = models.TextField('Descrição', blank=True)
    material = models.FileField('Material',upload_to='materials_course/', null=True, blank=True)
    activities = models.FileField('Atividades',upload_to='activities_course/', null=True, blank=True)
    is_visible = models.BooleanField(
        'Visível', default=False, blank=True
        )

    class Meta:
        verbose_name = 'Modulo'
        verbose_name_plural = 'Modulos'

    def get_absolute_url(self):
        return reverse('simplemooc:courses')

    def __str__(self):
        return self.name

# Função para atualização de imagens
def upload_location(instance, filename):
    return"%s/%s" %(instance.id, filename)

class Course(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    description = models.TextField('Descrição', blank=True)
    program = models.TextField('Programação', blank=True)
    qtd_available = models.IntegerField('Vagas')
    qtd_students = models.IntegerField('Alunos_matriculados')
    begin_matric = models.DateField('Inicio_inscrições', null=True, blank=True)
    end_matric = models.DateField('Fim_inscrições', null=True, blank=True)
    begin_course = models.DateField('Inicio_curso',  null=True, blank=True)
    end_course = models.DateField('Fim_curso',  null=True, blank=True)
    image = models.ImageField('Foto', upload_to=upload_location, null=True, blank=True)
    is_approved = models.BooleanField(
        'Aprovado', default=False, blank=True
        )
    teacher = models.ForeignKey(
        Teacher,
        related_name='courses',
        verbose_name='professor'
        )
    category = models.ForeignKey(
        Category,
        related_name='courses',
        verbose_name = 'categoria'
        )
    modules = models.ForeignKey(
        Modules,
        related_name='courses',
        blank=True,
        default=True,
        verbose_name='Modulos'
        )
    keywords =models.CharField('Palavras_chave', max_length=100, blank=True)

    class Meta:
        verbose_name = 'curso'
        verbose_name_plural = 'cursos'

    def get_absolute_url(self):
        return reverse('simplemooc:courses')

    def __str__(self):
        return self.name

simplemooc/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from .models import Category, Modules, Teacher, Course

class contact_form(forms.Form):
    name = forms.CharField(label='nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

class category_form(ModelForm):
    class Meta:
        model = Category
        fields = [
            'name',
            'slug'
        ]

class module_form(ModelForm):
    class Meta:
        model = Modules
        fields = [
            'name',
            'slug',
            'description',
            'material',
            'activities',
            'is_visible'
        ]

class teacher_form(ModelForm):
    class Meta:
        model = Teacher
        fields = [
        'name',
        'slug'
        ]

class course_form(ModelForm):
    class Meta:
        model = Course
        fields =[
        'name',
        'slug',
        'description',
        'program',
        'qtd_available',
        'qtd_students',
        'begin_matric',
        'end_matric',
        'begin_course',
        'end_course',
        'image',
        'is_approved',
        'teacher',
        'category',
        'modules',
        'keywords'
        ]

simplemooc/views.py
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView, CreateView, ListView, FormView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _
from django.core.mail import send_mail
from django.conf import settings
from rolepermissions.mixins import HasRoleMixin
from .forms import category_form, module_form, teacher_form, course_form, contact_form
from .models import Course, Category, Modules, Teacher

# Create your views here.
class HomeView(TemplateView):
    template_name = 'index.html'

class CourseView(ListView):
    template_name = 'courses.html'
    context_object_name = 'courses'
    paginate_by = 1

    def get_context_data(self, **kwargs):
        queryset = kwargs.pop('object_list', self.object_list)
        page_size = self.get_paginate_by(queryset)
        context_object_name = self.get_context_object_name(queryset)
        if page_size:
            paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, page_size)
            context = {
                'paginator': paginator,
                'page_obj': page,
                'is_paginated': is_paginated,
                'object_list': queryset
            }
        else:
            context = {
                'paginator': None,
                'page_obj': None,
                'is_paginated': False,
                'object_list': queryset
            }
        if context_object_name is not None:
            context[context_object_name] = queryset
            context['subscription'] = Course.objects.all()
        context.update(kwargs)
        return super(MultipleObjectMixin, self).get_context_data(**context)

    def get_queryset(self):
        u = self.request.user
        if u.is_authenticated():
            queryset = Course.objects.filter(user=self.request.user)
        else:
            queryset = Course.objects.all()

        q = self.request.GET.get('q', None)
        if q:
            queryset = queryset.filter(name__icontains=q)
        return queryset

class ShowCourseView(DetailView):
    model = Course
    context_object_name = 'course'
    template_name = 'course_detail.html'

class ShowCategoryView(DetailView):
    model = Category
    context_object_name = 'category'
    template_name = 'category.html'
    #falta carregar os cursos para a variável courses.

class CreateCategory(CreateView):
    model = Category
    form_class = category_form
    template_name = 'category_form.html'

class CreateModule(CreateView):
    model = Modules
    form_class = module_form
    template_name = 'module_form.html'

class CreateTeacher(CreateView):
    model = Teacher
    form_class = teacher_form
    template_name = 'teacher_form.html'

class CreateCourse(CreateView, HasRoleMixin):
    allowed_roles = [Teacher]
    model = Course
    form_class = course_form
    template_name = 'course_form.html'

class UpdateCourse(UpdateView):
    model = Course
    form_class = course_form
    template_name = 'course_form.html'

class DeleteCourse(DeleteView):
    model = Course
    template_name = 'course_confirm_delete.html'
    success_url = reverse_lazy('simplemooc:courses')

class ContactView(FormView):
   template_name = 'contact.html'
   form_class = contact_form
   success_url = reverse_lazy('simplemooc:contact')

   def form_valid(self, form):
    subject = '[simplemooc] {} entrou em contato'.format(form.cleaned_data['name'])
    message = 'E-mail: {}\n{}'.format(
        form.cleaned_data['email'], form.cleaned_data['message']
    )
    send_mail(
        subject, message, settings.DEFAULT_FROM_EMAIL, [settings.CONTACT_EMAIL]
    )
    return super(ContactView, self).form_valid(form)

simplemooc/templates/base.html
{% load static pagination i18n permission_tags %}

<html>

  <head>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Simple MOOC</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>

  <body>

    <header id="header" class="">

    </header><!-- /header -->

     <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'simplemooc:home' %}">{% simplemooc %}</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'simplemooc:home' %}">{% trans 'home' %}</a></li>
            <li><a href="{% url 'simplemooc:courses' %}">{% trans 'courses' %}</a></li>
            {% for cat in categories %}
            <li><a href="#">{{ cat }}</a></li>
            {% endfor %}
            <li><a href="{% url 'simplemooc:contact' %}">{% trans 'contact' %}</a></li>
          </ul>
          <form class="navbar-form navbar-left" action="{% url 'simplemooc:courses' %}" method="get" accept-charset="utf-8">
            <div class="form-group">
              <input class="form-control" type="text" placeholder="Pesquisar" name="q" />
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:edit_user' %}">{% trans ' + Subscription' %}</a></li>
              <li><a href="{% url 'accounts:edit_user' %}">{% trans 'Edit' %}</a></li>
              {% else %}
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

      <div class="container" style="margin-top: 3em;">
        <div class="starter-template">
          {% block content %}

          {% endblock %}
        </div>
      </div><!-- /.container -->

    <footer>

    </footer>
  </body>
</html>

simplemooc/templates/category.html
{% extends "base.html" %}
{% block content %}
<h1>Lista de Cursos por Categoria</h1>
<p><strong>Categoria selecionada: </strong>{{ category }}</p>
<p><strong>Cursos: </strong></p>
{% for course in courses %}
    <p>{{ course}}</p>
{% endfor%}

{% endblock%}

simplemooc/templates/category_form.html
{% extends "base.html" %}
{% block content %}
<h2>Cadastre uma Categoria</h2>
 {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
<form action=""  method="POST" accept-charset="utf-8">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" name="category_create_form" value="Registrar">
</form>
{% endblock %}

simplemooc/templates/contact.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Contato</h1>
        {% if success%}
            <div class="alert alert-success">
                Mensagem enviada com sucesso.
            </div>
        {% endif %}
        <form class="form-horizontal" action="" method="post">

            {% csrf_token %}
            {% for field in form %}
            <div class="form-group {% if  field.errors %}has-error{% endif %}">
                <label for="{{field.auto_id}}" class="col-sm-2 control-label">{{field.label}}</label>
                <div class="col-sm-10">
                    {% render_field field class='form-control' %}
                    {% for error in field.errors %}
                         <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>

        </form>
    </div>
</div>

{% endblock%}

simplemooc/templates/course_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

simplemooc/templates/course_form.html
{% extends "base.html" %}
{% block content %}
<h2>Cadastre um Curso</h2>
 {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
<form action=""  method="POST" accept-charset="utf-8">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" name="registermodule" value="Registrar">
</form>
{% endblock %}

simplemooc/templates/courses.html
{% extends "base.html" %}

{% load pagination %}

{% load permission_tags %}

{% block content %}
{% if user|can:'create_module' %}
<h3>Criar:</h3>
<p>
    <a class="btn btn-default btn-sm" href="{% url "simplemooc:createCourse" %}" role="button"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Curso</a>

    <a class="btn btn-default btn-sm" href="{% url "simplemooc:createCategory" %}" role="button"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Categoria</a>

    <a class="btn btn-default btn-sm" href="{% url "simplemooc:createModule" %}" role="button"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Módulo</a>

    <a class="btn btn-default btn-sm" href="{% url "simplemooc:createTeacher" %}" role="button"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>Professor</a>
</p>
{% endif %}
<h2>Lista de Cursos</h2>
{% for course in courses %}
<h3><a href="{% url 'simplemooc:detail' course.slug %}">{{ course }}</a></h3>
<p><i>{{ course.description|linebreaks  }}</i></p>
<p><strong>Categoria: </strong><a href="{% url 'simplemooc:category' course.category.slug %}">{{ course.category}}</a><br>
        <strong>Início: </strong>{{ course.begin_course }}<br>
        <strong>Fim: </strong>{{ course.end_course }}
</p>
<p>
    {% if user|has_role:'student, systemAdmin'%}
    <i>Inscrito</i> |
    {% endif %}
    <a href="{% url "simplemooc:updateCourse" course.slug %}">Editar</a> |
    <a href="{% url "simplemooc:deleteCourse" course.slug %}">Remover</a>
</p>
{% if user|has_role:'teacher' %}
<h4>Alunos Inscritos</h4>
<ul>
    <li></li>
</ul>
{% endif%}

{% endfor %}

{% pagination request paginator page_obj %}

<div class="col-md-4   ">
{% for sub in subscription%}
    <div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title"> {{sub}}</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-8 col-sm-6">
                <p>{{ sub.description|linebreaks  }}</p>
            </div>
            <div class="col-xs-4 col-sm-6">
                <p><a href="{% url "accounts:subscription" sub.slug %}"> + Inscreva-se</a></p>
            </div>
        </div>
    </div>
</div>

{% endfor %}
</div>
{% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
{% endblock%}

simplemooc/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="page-header">
    <div class="jumbotron" align="center">
        <h1>Simplemooc</h1>
        <p>Entre com sua conta e aproveite para se cadastrar nos cursos disponíveis</p>
        <p>
            {% if not user.is_authenticated %}
                <a class="btn btn-lg btn-success" href="{% url 'login' %}" role="button">Entrar</a>
            {% else %}
                <a class="btn btn-lg btn-success" href="{% url 'logout' %}" role="button">Sair</a>
            {% endif %}
        </p>
    </div>
</div>
{% endblock%}

simplemooc/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Entrar</h1>
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
                <label for="{{ field.auto_id }}" class="col-sm-4 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                  {% render_field field class='form-control' %}
                  {% for error in field.errors %}
                  <span class="help-block">{{ error }}</span>
                  {% endfor %}
                </div>
            </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                    <p><a href="{% url 'accounts:createUser' %}">Ainda não tem uma conta?</a></p>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-8">
                  <button type="submit" class="btn btn-primary">Entrar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/templates/moduleForm.html
{% extends "base.html" %}
{% block content %}
<h2>Cadastre um Modulo</h2>
 {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
<form action=""  method="POST" accept-charset="utf-8">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" name="registermodule" value="Registrar">
</form>
{% endblock %}

simplemooc/templates/module_form.html
{% extends "base.html" %}
{% block content %}
<h2>Cadastre um Modulo</h2>
 {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
<form action=""  method="POST" accept-charset="utf-8">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" name="registermodule" value="Registrar">
</form>
{% endblock %}

simplemooc/templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination">
    {% for page_number in paginator.page_range %}
    <li{% if page_obj.number == page_number %} class="active"{% endif %}>
        <a href="?page={{ page_number }}{{ getvars }}">{{ page_number }}</a>
    </li>
    {% endfor %}
  </ul>
</nav>

simplemooc/templates/teacherForm.html
{% extends "base.html" %}
{% block content %}
<h2>Cadastre um Professor</h2>
 {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
<form action=""  method="POST" accept-charset="utf-8">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" name="registermodule" value="Registrar">
</form>
{% endblock %}

simplemooc/templates/teacher_form.html
{% extends "base.html" %}
{% block content %}
<h2>Cadastre um Professor</h2>
 {% if success %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
{% endif %}
<form action=""  method="POST" accept-charset="utf-8">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" name="registermodule" value="Registrar">
</form>
{% endblock %}